import { createContext, useContext, useState, useEffect } from 'react'
import { Platform, I18nManager } from 'react-native'
import AsyncStorage from '@react-native-async-storage/async-storage'

export type LangCode = 'fr' | 'en' | 'ar' | 'es' | 'de' | 'pt'

const translations: Record<LangCode, Record<string, string>> = {
  fr: {
    // Navigation
    groups: 'Groupes',
    players: 'Joueurs',
    history: 'Historique',
    settings: 'Paramètres',
    // Groups
    newGroup: 'Nouveau groupe',
    joinWithCode: 'Rejoindre avec un code',
    noGroups: 'Aucun groupe pour l\'instant',
    createFirst: 'Crée ton premier groupe !',
    // Players
    addPlayer: 'Ajouter un joueur',
    noPlayers: 'Aucun joueur — ajoute le premier !',
    generateTeams: 'Générer les équipes',
    // Common
    back: '←',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    loading: 'Chargement...',
    error: 'Erreur',
    // Settings
    profile: 'Profil',
    nameFirstname: 'Nom & Prénom',
    preferences: 'Préférences',
    notifications: 'Notifications',
    language: 'Langue',
    appearance: 'Apparence',
    theme: 'Thème',
    application: 'Application',
    about: 'À propos',
    version: 'Version',
    legal: 'Légal',
    privacyPolicy: 'Politique de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    danger: 'Danger',
    resetApp: 'Réinitialiser l\'application',
    resetDesc: 'Supprime toutes tes données locales',
    // Tirage
    generatedTeams: 'Équipes générées',
    balance: 'Équilibre',
    reroll: 'Relancer',
    share: 'Partager',
    listView: 'Liste',
    pitchView: 'Terrain',
    // Groups page
    hello: 'Bonjour 👋',
    activeGroups: 'groupes actifs',
    myGroups: 'Mes groupes',
    active: 'Actif',
    // Group detail
    playersCount: 'joueurs',
    noPlayersYet: 'Aucun joueur — ajoute le premier !',
    addYourselfAsPlayer: 'Ce groupe a déjà des joueurs. Veux-tu t\'ajouter à la liste ?',
    generateTeamsMin: 'encore joueur(s)',
    minPlayersRequired: 'Minimum 4 joueurs requis',
    // Players
    reviewsReceived: 'Avis reçus',
    teammateReviews: 'Avis des coéquipiers',
    noReviews: 'Aucun avis pour l\'instant',
    shareRatingLink: 'Partage le lien de notation à tes coéquipiers',
    leaveReview: '+ Laisser un avis',
    matchesPlayed: 'Matchs joués',
    avgRating: 'Note moyenne',
    anonymous: 'Anonyme',
    teammate: 'Coéquipier',
    deletePlayer: 'Supprimer le joueur',
    irreversible: 'Cette action est irréversible.',
    notAllowed: 'Action non autorisée',
    // History
    noMatchYet: 'Aucun match encore',
    startFirst: 'Lance ton premier tirage !',
    // Join group
    joinGroup: 'Rejoindre un groupe',
    enterCode: 'Entre le code partagé par l\'admin du groupe',
    join: 'Rejoindre',
    searching: 'Recherche...',
    invalidCode: 'Code invalide — vérifie et réessaie',
    // New group
    createGroup: 'Créer un groupe',
    groupName: 'Nom du groupe',
    sport: 'Sport',
    emoji: 'Emoji',
    create: 'Créer',
    // Settings profile
    saveProfile: 'Sauvegarder',
    saved: '✓ Sauvegardé',
    saving: 'Sauvegarde...',
    yourProfile: 'Modifier tes informations',
    // Player form
    fullName: 'Nom complet',
    firstLastName: 'Prénom et nom',
    firstName: 'Prénom',
    lastName: 'Nom',
    initialRating: 'Note initiale',
    rating: 'Note',
    position: 'Poste',
    qualitiesOptional: 'Qualités (optionnel)',
    addPlayerLoading: 'Ajout en cours...',
    editPlayer: 'Modifier le joueur',
    // Review form
    overallRating: 'Note globale',
    commentOptional: 'Commentaire (optionnel)',
    commentPlaceholder: 'Dis ce que tu penses de ce joueur...',
    sendReview: 'Envoyer mon avis',
    sending: 'Envoi...',
    alreadyReviewed: 'Tu as déjà laissé un avis pour ce joueur',
    oneReviewOnly: 'Un seul avis par joueur est autorisé',
    ratingRequired: 'Donne une note avant de soumettre.',
    thankYouTitle: 'Merci !',
    reviewSaved: 'Ton avis a été enregistré !',
    leaveReviewSubtitle: 'Laisser un avis',
    backBtn: 'Retour',
    // Players list
    noPlayersInGroup: 'Aucun joueur',
    addPlayersFromGroup: "Ajoute des joueurs depuis la page d'un groupe",
    playersTotal: 'joueurs au total',
    searchPlayer: 'Rechercher un joueur...',
    noResultsFor: 'Aucun résultat pour',
    // New group
    newGroupTitle: 'Nouveau groupe',
    groupNamePlaceholder: 'Ex: Foot du mercredi',
    createGroupBtn: 'Créer le groupe',
    // Selection
    generateTeamsTitle: 'Générer les équipes',
    playersSelected: 'joueurs sélectionnés',
    numberOfTeams: "Nombre d'équipes",
    teamsLabel: 'équipes',
    // About
    aboutApp: "À propos de l'app",
    builtWith: 'Développé avec',
    featuresTitle: 'Fonctionnalités',
    madeWith: 'Fait avec ❤️ · 2026',
    // Language page
    chooseLanguage: "Choisir la langue de l'application",
    // Appearance
    chooseTheme: "Choisir le thème de l'application",
    darkModeActive: 'Mode sombre actif',
    lightModeActive: 'Mode clair actif',
    // Legal
    lastUpdated: 'Dernière mise à jour : janvier 2026',
    allRightsReserved: 'Squadra · Tous droits réservés · 2026',
    // Profile page
    personalInfo: 'Informations personnelles',
    yourFirstName: 'Ton prénom',
    yourLastName: 'Ton nom',
    yourProfileTitle: 'Ton profil',
    fieldRequired: 'Champ requis',
    enterNameMsg: 'Entre au moins un prénom ou un nom.',
    // Tags
    tagRapide: 'Rapide',
    tagTechnique: 'Technique',
    tagDefenseur: 'Défenseur',
    tagAttaquant: 'Attaquant',
    tagPasseur: 'Passeur',
    tagButeur: 'Buteur',
    tagLeader: 'Leader',
    tagRegulier: 'Régulier',
    tagAgressif: 'Agressif',
    tagFairPlay: 'Fair-play',
    // Theme modes
    themeLight: 'Clair',
    themeDark: 'Sombre',
    themeSystem: 'Système',
  },
  en: {
    groups: 'Groups',
    players: 'Players',
    history: 'History',
    settings: 'Settings',
    newGroup: 'New group',
    joinWithCode: 'Join with a code',
    noGroups: 'No groups yet',
    createFirst: 'Create your first group!',
    addPlayer: 'Add player',
    noPlayers: 'No players — add the first one!',
    generateTeams: 'Generate teams',
    back: '←',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    error: 'Error',
    profile: 'Profile',
    nameFirstname: 'Name & First name',
    preferences: 'Preferences',
    notifications: 'Notifications',
    language: 'Language',
    appearance: 'Appearance',
    theme: 'Theme',
    application: 'Application',
    about: 'About',
    version: 'Version',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    danger: 'Danger',
    resetApp: 'Reset application',
    resetDesc: 'Deletes all your local data',
    generatedTeams: 'Generated teams',
    balance: 'Balance',
    reroll: 'Reroll',
    share: 'Share',
    listView: 'List',
    pitchView: 'Pitch',
    // Groups page
    hello: 'Hello 👋',
    activeGroups: 'active groups',
    myGroups: 'My groups',
    active: 'Active',
    // Group detail
    playersCount: 'players',
    noPlayersYet: 'No players yet!',
    addYourselfAsPlayer: 'This group already has players. Do you want to add yourself?',
    generateTeamsMin: 'more player(s) needed',
    minPlayersRequired: 'Minimum 4 players required',
    // Players
    reviewsReceived: 'Reviews received',
    teammateReviews: 'Teammate reviews',
    noReviews: 'No reviews yet',
    shareRatingLink: 'Share your rating link with teammates',
    leaveReview: '+ Leave a review',
    matchesPlayed: 'Matches played',
    avgRating: 'Average rating',
    anonymous: 'Anonymous',
    teammate: 'Teammate',
    deletePlayer: 'Delete player',
    irreversible: 'This action is irreversible.',
    notAllowed: 'Action not allowed',
    // History
    noMatchYet: 'No matches yet',
    startFirst: 'Start your first draw!',
    // Join group
    joinGroup: 'Join a group',
    enterCode: 'Enter the code shared by the group admin',
    join: 'Join',
    searching: 'Searching...',
    invalidCode: 'Invalid code — check and try again',
    // New group
    createGroup: 'Create a group',
    groupName: 'Group name',
    sport: 'Sport',
    emoji: 'Emoji',
    create: 'Create',
    // Settings profile
    saveProfile: 'Save',
    saved: '✓ Saved',
    saving: 'Saving...',
    yourProfile: 'Edit your info',
    // Player form
    fullName: 'Full name',
    firstLastName: 'First and last name',
    firstName: 'First name',
    lastName: 'Last name',
    initialRating: 'Initial rating',
    rating: 'Rating',
    position: 'Position',
    qualitiesOptional: 'Qualities (optional)',
    addPlayerLoading: 'Adding...',
    editPlayer: 'Edit player',
    // Review form
    overallRating: 'Overall rating',
    commentOptional: 'Comment (optional)',
    commentPlaceholder: 'Share your thoughts about this player...',
    sendReview: 'Submit review',
    sending: 'Sending...',
    alreadyReviewed: 'You have already left a review for this player',
    oneReviewOnly: 'Only one review per player is allowed',
    ratingRequired: 'Please give a rating before submitting.',
    thankYouTitle: 'Thank you!',
    reviewSaved: 'Your review has been saved!',
    leaveReviewSubtitle: 'Leave a review',
    backBtn: 'Back',
    // Players list
    noPlayersInGroup: 'No players',
    addPlayersFromGroup: 'Add players from a group page',
    playersTotal: 'players total',
    searchPlayer: 'Search a player...',
    noResultsFor: 'No results for',
    // New group
    newGroupTitle: 'New group',
    groupNamePlaceholder: 'E.g.: Wednesday football',
    createGroupBtn: 'Create group',
    // Selection
    generateTeamsTitle: 'Generate teams',
    playersSelected: 'players selected',
    numberOfTeams: 'Number of teams',
    teamsLabel: 'teams',
    // About
    aboutApp: 'About the app',
    builtWith: 'Built with',
    featuresTitle: 'Features',
    madeWith: 'Made with ❤️ · 2026',
    // Language page
    chooseLanguage: 'Choose the app language',
    // Appearance
    chooseTheme: 'Choose the app theme',
    darkModeActive: 'Dark mode active',
    lightModeActive: 'Light mode active',
    // Legal
    lastUpdated: 'Last updated: January 2026',
    allRightsReserved: 'Squadra · All rights reserved · 2026',
    // Profile page
    personalInfo: 'Personal information',
    yourFirstName: 'Your first name',
    yourLastName: 'Your last name',
    yourProfileTitle: 'Your profile',
    fieldRequired: 'Required field',
    enterNameMsg: 'Please enter at least a first name or last name.',
    // Tags
    tagRapide: 'Fast',
    tagTechnique: 'Technical',
    tagDefenseur: 'Defender',
    tagAttaquant: 'Attacker',
    tagPasseur: 'Playmaker',
    tagButeur: 'Scorer',
    tagLeader: 'Leader',
    tagRegulier: 'Consistent',
    tagAgressif: 'Aggressive',
    tagFairPlay: 'Fair play',
    // Theme modes
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
  },
  ar: {
    groups: 'المجموعات',
    players: 'اللاعبون',
    history: 'السجل',
    settings: 'الإعدادات',
    newGroup: 'مجموعة جديدة',
    joinWithCode: 'الانضمام برمز',
    noGroups: 'لا توجد مجموعات بعد',
    createFirst: 'أنشئ مجموعتك الأولى!',
    addPlayer: 'إضافة لاعب',
    noPlayers: 'لا يوجد لاعبون — أضف الأول!',
    generateTeams: 'توليد الفرق',
    back: '→',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    confirm: 'تأكيد',
    loading: 'جار التحميل...',
    error: 'خطأ',
    profile: 'الملف الشخصي',
    nameFirstname: 'الاسم والاسم الأول',
    preferences: 'التفضيلات',
    notifications: 'الإشعارات',
    language: 'اللغة',
    appearance: 'المظهر',
    theme: 'السمة',
    application: 'التطبيق',
    about: 'حول',
    version: 'الإصدار',
    legal: 'قانوني',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الاستخدام',
    danger: 'خطر',
    resetApp: 'إعادة تعيين التطبيق',
    resetDesc: 'يحذف جميع بياناتك المحلية',
    generatedTeams: 'الفرق المولّدة',
    balance: 'توازن',
    reroll: 'إعادة السحب',
    share: 'مشاركة',
    listView: 'قائمة',
    pitchView: 'الملعب',
    // Groups page
    hello: 'مرحبا 👋',
    activeGroups: 'مجموعات نشطة',
    myGroups: 'مجموعاتي',
    active: 'نشط',
    // Group detail
    playersCount: 'لاعبون',
    noPlayersYet: 'لا يوجد لاعبون بعد!',
    addYourselfAsPlayer: 'يحتوي هذا الفريق على لاعبين. هل تريد إضافة نفسك؟',
    generateTeamsMin: 'لاعب(ون) إضافي(ون)',
    minPlayersRequired: 'الحد الأدنى 4 لاعبين مطلوب',
    // Players
    reviewsReceived: 'التقييمات المستلمة',
    teammateReviews: 'تقييمات الزملاء',
    noReviews: 'لا توجد تقييمات بعد',
    shareRatingLink: 'شارك رابط التقييم مع زملائك',
    leaveReview: '+ اترك تقييماً',
    matchesPlayed: 'المباريات المُلعبة',
    avgRating: 'متوسط التقييم',
    anonymous: 'مجهول',
    teammate: 'زميل',
    deletePlayer: 'حذف اللاعب',
    irreversible: 'هذا الإجراء لا رجعة فيه.',
    notAllowed: 'الإجراء غير مسموح به',
    // History
    noMatchYet: 'لا توجد مباريات بعد',
    startFirst: 'ابدأ أول سحب!',
    // Join group
    joinGroup: 'الانضمام إلى مجموعة',
    enterCode: 'أدخل الرمز الذي شاركه مسؤول المجموعة',
    join: 'انضمام',
    searching: 'جارٍ البحث...',
    invalidCode: 'رمز غير صالح — تحقق وحاول مجدداً',
    // New group
    createGroup: 'إنشاء مجموعة',
    groupName: 'اسم المجموعة',
    sport: 'رياضة',
    emoji: 'إيموجي',
    create: 'إنشاء',
    // Settings profile
    saveProfile: 'حفظ',
    saved: '✓ تم الحفظ',
    saving: 'جار الحفظ...',
    yourProfile: 'تعديل معلوماتك',
    // Player form
    fullName: 'الاسم الكامل',
    firstLastName: 'الاسم الأول واسم العائلة',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    initialRating: 'التقييم الأولي',
    rating: 'التقييم',
    position: 'المركز',
    qualitiesOptional: 'المميزات (اختياري)',
    addPlayerLoading: 'جار الإضافة...',
    editPlayer: 'تعديل اللاعب',
    // Review form
    overallRating: 'التقييم العام',
    commentOptional: 'تعليق (اختياري)',
    commentPlaceholder: 'شارك رأيك حول هذا اللاعب...',
    sendReview: 'إرسال تقييمي',
    sending: 'جار الإرسال...',
    alreadyReviewed: 'لقد تركت تقييماً لهذا اللاعب من قبل',
    oneReviewOnly: 'يُسمح بتقييم واحد فقط لكل لاعب',
    ratingRequired: 'يرجى إعطاء تقييم قبل الإرسال.',
    thankYouTitle: 'شكراً!',
    reviewSaved: 'تم حفظ تقييمك!',
    leaveReviewSubtitle: 'اترك تقييماً',
    backBtn: 'رجوع',
    // Players list
    noPlayersInGroup: 'لا يوجد لاعبون',
    addPlayersFromGroup: 'أضف لاعبين من صفحة مجموعة',
    playersTotal: 'لاعب في المجموع',
    searchPlayer: 'ابحث عن لاعب...',
    noResultsFor: 'لا توجد نتائج لـ',
    // New group
    newGroupTitle: 'مجموعة جديدة',
    groupNamePlaceholder: 'مثال: كرة القدم الأربعاء',
    createGroupBtn: 'إنشاء المجموعة',
    // Selection
    generateTeamsTitle: 'توليد الفرق',
    playersSelected: 'لاعب مختار',
    numberOfTeams: 'عدد الفرق',
    teamsLabel: 'فرق',
    // About
    aboutApp: 'حول التطبيق',
    builtWith: 'مبني بـ',
    featuresTitle: 'الميزات',
    madeWith: 'صُنع بـ ❤️ · 2026',
    // Language page
    chooseLanguage: 'اختر لغة التطبيق',
    // Appearance
    chooseTheme: 'اختر مظهر التطبيق',
    darkModeActive: 'الوضع الداكن مفعّل',
    lightModeActive: 'الوضع الفاتح مفعّل',
    // Legal
    lastUpdated: 'آخر تحديث: يناير 2026',
    allRightsReserved: 'Squadra · جميع الحقوق محفوظة · 2026',
    // Profile page
    personalInfo: 'المعلومات الشخصية',
    yourFirstName: 'اسمك الأول',
    yourLastName: 'اسم عائلتك',
    yourProfileTitle: 'ملفك الشخصي',
    fieldRequired: 'حقل مطلوب',
    enterNameMsg: 'يرجى إدخال اسم أول أو اسم عائلة على الأقل.',
    // Tags
    tagRapide: 'سريع',
    tagTechnique: 'تقني',
    tagDefenseur: 'مدافع',
    tagAttaquant: 'مهاجم',
    tagPasseur: 'صانع اللعب',
    tagButeur: 'مسجل أهداف',
    tagLeader: 'قائد',
    tagRegulier: 'منتظم',
    tagAgressif: 'عدواني',
    tagFairPlay: 'لعب نظيف',
    // Theme modes
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'تلقائي',
  },
  es: {
    groups: 'Grupos',
    players: 'Jugadores',
    history: 'Historial',
    settings: 'Ajustes',
    newGroup: 'Nuevo grupo',
    joinWithCode: 'Unirse con código',
    noGroups: 'Sin grupos aún',
    createFirst: '¡Crea tu primer grupo!',
    addPlayer: 'Añadir jugador',
    noPlayers: 'Sin jugadores — ¡añade el primero!',
    generateTeams: 'Generar equipos',
    back: '←',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    loading: 'Cargando...',
    error: 'Error',
    profile: 'Perfil',
    nameFirstname: 'Nombre y Apellido',
    preferences: 'Preferencias',
    notifications: 'Notificaciones',
    language: 'Idioma',
    appearance: 'Apariencia',
    theme: 'Tema',
    application: 'Aplicación',
    about: 'Acerca de',
    version: 'Versión',
    legal: 'Legal',
    privacyPolicy: 'Política de privacidad',
    termsOfService: 'Términos de uso',
    danger: 'Peligro',
    resetApp: 'Restablecer aplicación',
    resetDesc: 'Elimina todos tus datos locales',
    generatedTeams: 'Equipos generados',
    balance: 'Equilibrio',
    reroll: 'Relanzar',
    share: 'Compartir',
    listView: 'Lista',
    pitchView: 'Campo',
    // Groups page
    hello: 'Hola 👋',
    activeGroups: 'grupos activos',
    myGroups: 'Mis grupos',
    active: 'Activo',
    // Group detail
    playersCount: 'jugadores',
    noPlayersYet: '¡Sin jugadores aún!',
    addYourselfAsPlayer: 'Este grupo ya tiene jugadores. ¿Quieres añadirte?',
    generateTeamsMin: 'jugador(es) más',
    minPlayersRequired: 'Mínimo 4 jugadores requeridos',
    // Players
    reviewsReceived: 'Reseñas recibidas',
    teammateReviews: 'Reseñas de compañeros',
    noReviews: 'Sin reseñas aún',
    shareRatingLink: 'Comparte el enlace de calificación',
    leaveReview: '+ Dejar reseña',
    matchesPlayed: 'Partidos jugados',
    avgRating: 'Calificación media',
    anonymous: 'Anónimo',
    teammate: 'Compañero',
    deletePlayer: 'Eliminar jugador',
    irreversible: 'Esta acción es irreversible.',
    notAllowed: 'Acción no permitida',
    // History
    noMatchYet: 'Sin partidos aún',
    startFirst: '¡Empieza tu primer sorteo!',
    // Join group
    joinGroup: 'Unirse a un grupo',
    enterCode: 'Ingresa el código del administrador',
    join: 'Unirse',
    searching: 'Buscando...',
    invalidCode: 'Código inválido — verifica y reintenta',
    // New group
    createGroup: 'Crear un grupo',
    groupName: 'Nombre del grupo',
    sport: 'Deporte',
    emoji: 'Emoji',
    create: 'Crear',
    // Settings profile
    saveProfile: 'Guardar',
    saved: '✓ Guardado',
    saving: 'Guardando...',
    yourProfile: 'Editar tu información',
    // Player form
    fullName: 'Nombre completo',
    firstLastName: 'Nombre y apellido',
    firstName: 'Nombre',
    lastName: 'Apellido',
    initialRating: 'Calificación inicial',
    rating: 'Calificación',
    position: 'Posición',
    qualitiesOptional: 'Cualidades (opcional)',
    addPlayerLoading: 'Añadiendo...',
    editPlayer: 'Editar jugador',
    // Review form
    overallRating: 'Calificación general',
    commentOptional: 'Comentario (opcional)',
    commentPlaceholder: 'Comparte tu opinión sobre este jugador...',
    sendReview: 'Enviar reseña',
    sending: 'Enviando...',
    alreadyReviewed: 'Ya dejaste una reseña para este jugador',
    oneReviewOnly: 'Solo se permite una reseña por jugador',
    ratingRequired: 'Da una calificación antes de enviar.',
    thankYouTitle: '¡Gracias!',
    reviewSaved: '¡Tu reseña ha sido guardada!',
    leaveReviewSubtitle: 'Dejar una reseña',
    backBtn: 'Volver',
    // Players list
    noPlayersInGroup: 'Sin jugadores',
    addPlayersFromGroup: 'Añade jugadores desde la página de un grupo',
    playersTotal: 'jugadores en total',
    searchPlayer: 'Buscar un jugador...',
    noResultsFor: 'Sin resultados para',
    // New group
    newGroupTitle: 'Nuevo grupo',
    groupNamePlaceholder: 'Ej: Fútbol del miércoles',
    createGroupBtn: 'Crear el grupo',
    // Selection
    generateTeamsTitle: 'Generar equipos',
    playersSelected: 'jugadores seleccionados',
    numberOfTeams: 'Número de equipos',
    teamsLabel: 'equipos',
    // About
    aboutApp: 'Sobre la app',
    builtWith: 'Desarrollado con',
    featuresTitle: 'Funcionalidades',
    madeWith: 'Hecho con ❤️ · 2026',
    // Language page
    chooseLanguage: 'Elegir el idioma de la aplicación',
    // Appearance
    chooseTheme: 'Elegir el tema de la aplicación',
    darkModeActive: 'Modo oscuro activo',
    lightModeActive: 'Modo claro activo',
    // Legal
    lastUpdated: 'Última actualización: enero 2026',
    allRightsReserved: 'Squadra · Todos los derechos reservados · 2026',
    // Profile page
    personalInfo: 'Información personal',
    yourFirstName: 'Tu nombre',
    yourLastName: 'Tu apellido',
    yourProfileTitle: 'Tu perfil',
    fieldRequired: 'Campo requerido',
    enterNameMsg: 'Introduce al menos un nombre o apellido.',
    // Tags
    tagRapide: 'Rápido',
    tagTechnique: 'Técnico',
    tagDefenseur: 'Defensor',
    tagAttaquant: 'Delantero',
    tagPasseur: 'Pasador',
    tagButeur: 'Goleador',
    tagLeader: 'Líder',
    tagRegulier: 'Regular',
    tagAgressif: 'Agresivo',
    tagFairPlay: 'Juego limpio',
    // Theme modes
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeSystem: 'Sistema',
  },
  de: {
    groups: 'Gruppen',
    players: 'Spieler',
    history: 'Verlauf',
    settings: 'Einstellungen',
    newGroup: 'Neue Gruppe',
    joinWithCode: 'Mit Code beitreten',
    noGroups: 'Noch keine Gruppen',
    createFirst: 'Erstelle deine erste Gruppe!',
    addPlayer: 'Spieler hinzufügen',
    noPlayers: 'Keine Spieler — füge den ersten hinzu!',
    generateTeams: 'Teams generieren',
    back: '←',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    confirm: 'Bestätigen',
    loading: 'Laden...',
    error: 'Fehler',
    profile: 'Profil',
    nameFirstname: 'Name & Vorname',
    preferences: 'Einstellungen',
    notifications: 'Benachrichtigungen',
    language: 'Sprache',
    appearance: 'Erscheinungsbild',
    theme: 'Thema',
    application: 'Anwendung',
    about: 'Über',
    version: 'Version',
    legal: 'Rechtliches',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    danger: 'Gefahr',
    resetApp: 'App zurücksetzen',
    resetDesc: 'Löscht alle lokalen Daten',
    generatedTeams: 'Generierte Teams',
    balance: 'Balance',
    reroll: 'Neu würfeln',
    share: 'Teilen',
    listView: 'Liste',
    pitchView: 'Spielfeld',
    // Groups page
    hello: 'Hallo 👋',
    activeGroups: 'aktive Gruppen',
    myGroups: 'Meine Gruppen',
    active: 'Aktiv',
    // Group detail
    playersCount: 'Spieler',
    noPlayersYet: 'Noch keine Spieler!',
    addYourselfAsPlayer: 'Diese Gruppe hat bereits Spieler. Möchtest du dich hinzufügen?',
    generateTeamsMin: 'Spieler fehlen noch',
    minPlayersRequired: 'Mindestens 4 Spieler erforderlich',
    // Players
    reviewsReceived: 'Erhaltene Bewertungen',
    teammateReviews: 'Bewertungen der Mitspieler',
    noReviews: 'Noch keine Bewertungen',
    shareRatingLink: 'Teile den Bewertungslink',
    leaveReview: '+ Bewertung hinterlassen',
    matchesPlayed: 'Gespielte Spiele',
    avgRating: 'Durchschnittsnote',
    anonymous: 'Anonym',
    teammate: 'Mitspieler',
    deletePlayer: 'Spieler löschen',
    irreversible: 'Diese Aktion ist unwiderruflich.',
    notAllowed: 'Aktion nicht erlaubt',
    // History
    noMatchYet: 'Noch keine Spiele',
    startFirst: 'Starte deinen ersten Zug!',
    // Join group
    joinGroup: 'Gruppe beitreten',
    enterCode: 'Gib den Code des Administrators ein',
    join: 'Beitreten',
    searching: 'Suche...',
    invalidCode: 'Ungültiger Code — prüfen und erneut versuchen',
    // New group
    createGroup: 'Gruppe erstellen',
    groupName: 'Gruppenname',
    sport: 'Sport',
    emoji: 'Emoji',
    create: 'Erstellen',
    // Settings profile
    saveProfile: 'Speichern',
    saved: '✓ Gespeichert',
    saving: 'Speichern...',
    yourProfile: 'Deine Infos bearbeiten',
    // Player form
    fullName: 'Vollständiger Name',
    firstLastName: 'Vor- und Nachname',
    firstName: 'Vorname',
    lastName: 'Nachname',
    initialRating: 'Anfangsbewertung',
    rating: 'Bewertung',
    position: 'Position',
    qualitiesOptional: 'Qualitäten (optional)',
    addPlayerLoading: 'Hinzufügen...',
    editPlayer: 'Spieler bearbeiten',
    // Review form
    overallRating: 'Gesamtbewertung',
    commentOptional: 'Kommentar (optional)',
    commentPlaceholder: 'Teile deine Meinung über diesen Spieler...',
    sendReview: 'Bewertung abschicken',
    sending: 'Senden...',
    alreadyReviewed: 'Du hast bereits eine Bewertung für diesen Spieler hinterlassen',
    oneReviewOnly: 'Nur eine Bewertung pro Spieler ist erlaubt',
    ratingRequired: 'Gib eine Bewertung vor dem Abschicken.',
    thankYouTitle: 'Danke!',
    reviewSaved: 'Deine Bewertung wurde gespeichert!',
    leaveReviewSubtitle: 'Bewertung hinterlassen',
    backBtn: 'Zurück',
    // Players list
    noPlayersInGroup: 'Keine Spieler',
    addPlayersFromGroup: 'Füge Spieler über eine Gruppenseite hinzu',
    playersTotal: 'Spieler insgesamt',
    searchPlayer: 'Spieler suchen...',
    noResultsFor: 'Keine Ergebnisse für',
    // New group
    newGroupTitle: 'Neue Gruppe',
    groupNamePlaceholder: 'Z.B.: Mittwoch-Fußball',
    createGroupBtn: 'Gruppe erstellen',
    // Selection
    generateTeamsTitle: 'Teams generieren',
    playersSelected: 'Spieler ausgewählt',
    numberOfTeams: 'Anzahl Teams',
    teamsLabel: 'Teams',
    // About
    aboutApp: 'Über die App',
    builtWith: 'Entwickelt mit',
    featuresTitle: 'Funktionen',
    madeWith: 'Gemacht mit ❤️ · 2026',
    // Language page
    chooseLanguage: 'App-Sprache auswählen',
    // Appearance
    chooseTheme: 'App-Thema auswählen',
    darkModeActive: 'Dunkelmodus aktiv',
    lightModeActive: 'Hellmodus aktiv',
    // Legal
    lastUpdated: 'Zuletzt aktualisiert: Januar 2026',
    allRightsReserved: 'Squadra · Alle Rechte vorbehalten · 2026',
    // Profile page
    personalInfo: 'Persönliche Informationen',
    yourFirstName: 'Dein Vorname',
    yourLastName: 'Dein Nachname',
    yourProfileTitle: 'Dein Profil',
    fieldRequired: 'Pflichtfeld',
    enterNameMsg: 'Gib mindestens einen Vor- oder Nachnamen ein.',
    // Tags
    tagRapide: 'Schnell',
    tagTechnique: 'Technisch',
    tagDefenseur: 'Verteidiger',
    tagAttaquant: 'Stürmer',
    tagPasseur: 'Passgeber',
    tagButeur: 'Torschütze',
    tagLeader: 'Anführer',
    tagRegulier: 'Beständig',
    tagAgressif: 'Aggressiv',
    tagFairPlay: 'Faires Spiel',
    // Theme modes
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    themeSystem: 'System',
  },
  pt: {
    groups: 'Grupos',
    players: 'Jogadores',
    history: 'Histórico',
    settings: 'Configurações',
    newGroup: 'Novo grupo',
    joinWithCode: 'Entrar com código',
    noGroups: 'Nenhum grupo ainda',
    createFirst: 'Crie seu primeiro grupo!',
    addPlayer: 'Adicionar jogador',
    noPlayers: 'Nenhum jogador — adicione o primeiro!',
    generateTeams: 'Gerar equipes',
    back: '←',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    loading: 'Carregando...',
    error: 'Erro',
    profile: 'Perfil',
    nameFirstname: 'Nome e Sobrenome',
    preferences: 'Preferências',
    notifications: 'Notificações',
    language: 'Idioma',
    appearance: 'Aparência',
    theme: 'Tema',
    application: 'Aplicativo',
    about: 'Sobre',
    version: 'Versão',
    legal: 'Legal',
    privacyPolicy: 'Política de privacidade',
    termsOfService: 'Termos de uso',
    danger: 'Perigo',
    resetApp: 'Redefinir aplicativo',
    resetDesc: 'Exclui todos os seus dados locais',
    generatedTeams: 'Equipes geradas',
    balance: 'Equilíbrio',
    reroll: 'Rolar novamente',
    share: 'Compartilhar',
    listView: 'Lista',
    pitchView: 'Campo',
    // Groups page
    hello: 'Olá 👋',
    activeGroups: 'grupos ativos',
    myGroups: 'Meus grupos',
    active: 'Ativo',
    // Group detail
    playersCount: 'jogadores',
    noPlayersYet: 'Sem jogadores ainda!',
    addYourselfAsPlayer: 'Este grupo já tem jogadores. Deseja se adicionar?',
    generateTeamsMin: 'jogador(es) a mais',
    minPlayersRequired: 'Mínimo 4 jogadores necessários',
    // Players
    reviewsReceived: 'Avaliações recebidas',
    teammateReviews: 'Avaliações dos colegas',
    noReviews: 'Sem avaliações ainda',
    shareRatingLink: 'Compartilhe o link de avaliação',
    leaveReview: '+ Deixar avaliação',
    matchesPlayed: 'Partidas jogadas',
    avgRating: 'Nota média',
    anonymous: 'Anônimo',
    teammate: 'Colega',
    deletePlayer: 'Excluir jogador',
    irreversible: 'Esta ação é irreversível.',
    notAllowed: 'Ação não permitida',
    // History
    noMatchYet: 'Sem partidas ainda',
    startFirst: 'Comece seu primeiro sorteio!',
    // Join group
    joinGroup: 'Entrar em um grupo',
    enterCode: 'Digite o código do administrador',
    join: 'Entrar',
    searching: 'Pesquisando...',
    invalidCode: 'Código inválido — verifique e tente novamente',
    // New group
    createGroup: 'Criar um grupo',
    groupName: 'Nome do grupo',
    sport: 'Esporte',
    emoji: 'Emoji',
    create: 'Criar',
    // Settings profile
    saveProfile: 'Salvar',
    saved: '✓ Salvo',
    saving: 'Salvando...',
    yourProfile: 'Editar suas informações',
    // Player form
    fullName: 'Nome completo',
    firstLastName: 'Nome e sobrenome',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    initialRating: 'Avaliação inicial',
    rating: 'Avaliação',
    position: 'Posição',
    qualitiesOptional: 'Qualidades (opcional)',
    addPlayerLoading: 'Adicionando...',
    editPlayer: 'Editar jogador',
    // Review form
    overallRating: 'Avaliação geral',
    commentOptional: 'Comentário (opcional)',
    commentPlaceholder: 'Compartilhe sua opinião sobre este jogador...',
    sendReview: 'Enviar avaliação',
    sending: 'Enviando...',
    alreadyReviewed: 'Você já deixou uma avaliação para este jogador',
    oneReviewOnly: 'Apenas uma avaliação por jogador é permitida',
    ratingRequired: 'Dê uma avaliação antes de enviar.',
    thankYouTitle: 'Obrigado!',
    reviewSaved: 'Sua avaliação foi salva!',
    leaveReviewSubtitle: 'Deixar uma avaliação',
    backBtn: 'Voltar',
    // Players list
    noPlayersInGroup: 'Nenhum jogador',
    addPlayersFromGroup: 'Adicione jogadores pela página de um grupo',
    playersTotal: 'jogadores no total',
    searchPlayer: 'Pesquisar um jogador...',
    noResultsFor: 'Nenhum resultado para',
    // New group
    newGroupTitle: 'Novo grupo',
    groupNamePlaceholder: 'Ex: Futebol de quarta',
    createGroupBtn: 'Criar o grupo',
    // Selection
    generateTeamsTitle: 'Gerar equipes',
    playersSelected: 'jogadores selecionados',
    numberOfTeams: 'Número de equipes',
    teamsLabel: 'equipes',
    // About
    aboutApp: 'Sobre o app',
    builtWith: 'Desenvolvido com',
    featuresTitle: 'Funcionalidades',
    madeWith: 'Feito com ❤️ · 2026',
    // Language page
    chooseLanguage: 'Escolher o idioma do aplicativo',
    // Appearance
    chooseTheme: 'Escolher o tema do aplicativo',
    darkModeActive: 'Modo escuro ativo',
    lightModeActive: 'Modo claro ativo',
    // Legal
    lastUpdated: 'Última atualização: janeiro de 2026',
    allRightsReserved: 'Squadra · Todos os direitos reservados · 2026',
    // Profile page
    personalInfo: 'Informações pessoais',
    yourFirstName: 'Seu nome',
    yourLastName: 'Seu sobrenome',
    yourProfileTitle: 'Seu perfil',
    fieldRequired: 'Campo obrigatório',
    enterNameMsg: 'Insira pelo menos um nome ou sobrenome.',
    // Tags
    tagRapide: 'Rápido',
    tagTechnique: 'Técnico',
    tagDefenseur: 'Defensor',
    tagAttaquant: 'Atacante',
    tagPasseur: 'Passador',
    tagButeur: 'Artilheiro',
    tagLeader: 'Líder',
    tagRegulier: 'Regular',
    tagAgressif: 'Agressivo',
    tagFairPlay: 'Jogo limpo',
    // Theme modes
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
  },
}

interface LanguageContextType {
  lang: LangCode
  t: (key: string) => string
  setLang: (lang: LangCode) => void
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  t: (key) => key,
  setLang: () => {},
  isRTL: false,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('fr')

  useEffect(() => {
    async function load() {
      const saved = Platform.OS === 'web'
        ? localStorage.getItem('app_langue')
        : await AsyncStorage.getItem('app_langue')
      if (saved && saved in translations) {
        const savedLang = saved as LangCode
        setLangState(savedLang)
        if (Platform.OS !== 'web') {
          const shouldBeRTL = savedLang === 'ar'
          if (I18nManager.isRTL !== shouldBeRTL) {
            I18nManager.forceRTL(shouldBeRTL)
          }
        }
      }
    }
    load()
  }, [])

  async function setLang(newLang: LangCode) {
    setLangState(newLang)
    if (Platform.OS === 'web') {
      localStorage.setItem('app_langue', newLang)
    } else {
      await AsyncStorage.setItem('app_langue', newLang)
      const shouldBeRTL = newLang === 'ar'
      if (I18nManager.isRTL !== shouldBeRTL) {
        I18nManager.forceRTL(shouldBeRTL)
      }
    }
  }

  function t(key: string): string {
    return translations[lang]?.[key] ?? translations['fr']?.[key] ?? key
  }

  const isRTL = lang === 'ar'

  return (
    <LanguageContext.Provider value={{ lang, t, setLang, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
